package com.example.demo.dao;

import java.io.Serializable;
import java.util.Date;

public class FxUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.id
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.user_name
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.first_name
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.last_name
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.gender
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.address
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.class_name
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.father_id
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    private Long fatherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.mother_id
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    private Long motherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.creater_time
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    private Date createrTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fx_user
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.id
     *
     * @return the value of fx_user.id
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.id
     *
     * @param id the value for fx_user.id
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.user_name
     *
     * @return the value of fx_user.user_name
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.user_name
     *
     * @param userName the value for fx_user.user_name
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.first_name
     *
     * @return the value of fx_user.first_name
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.first_name
     *
     * @param firstName the value for fx_user.first_name
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.last_name
     *
     * @return the value of fx_user.last_name
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.last_name
     *
     * @param lastName the value for fx_user.last_name
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.gender
     *
     * @return the value of fx_user.gender
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.gender
     *
     * @param gender the value for fx_user.gender
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.address
     *
     * @return the value of fx_user.address
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.address
     *
     * @param address the value for fx_user.address
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.class_name
     *
     * @return the value of fx_user.class_name
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.class_name
     *
     * @param className the value for fx_user.class_name
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.father_id
     *
     * @return the value of fx_user.father_id
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public Long getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.father_id
     *
     * @param fatherId the value for fx_user.father_id
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public void setFatherId(Long fatherId) {
        this.fatherId = fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.mother_id
     *
     * @return the value of fx_user.mother_id
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public Long getMotherId() {
        return motherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.mother_id
     *
     * @param motherId the value for fx_user.mother_id
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public void setMotherId(Long motherId) {
        this.motherId = motherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.creater_time
     *
     * @return the value of fx_user.creater_time
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public Date getCreaterTime() {
        return createrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.creater_time
     *
     * @param createrTime the value for fx_user.creater_time
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    public void setCreaterTime(Date createrTime) {
        this.createrTime = createrTime;
    }
}