package com.example.demo.dao;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class IqUsers implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.mobile
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.avatar
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.token
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Integer token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.longitude
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.latitude
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.address
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.signature
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.sex
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.birthday
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.city
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.adcode
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String adcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.citycode
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String citycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.user_type
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Byte userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.evaluate
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private BigDecimal evaluate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.follow_nums
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Long followNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.follow_me_nums
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Long followMeNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.group_nums
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Long groupNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.like_nums
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Long likeNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.like_me_nums
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Long likeMeNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.rong_cloud_token
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String rongCloudToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.rong_cloud_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String rongCloudId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.ayg_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String aygId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.user_status
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Byte userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.email
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.password
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.created_at
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.updated_at
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.card_no
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.card_front_image
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String cardFrontImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.card_back_image
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String cardBackImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.real_name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.alipay_payee_type
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String alipayPayeeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.alipay_payee_user_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String alipayPayeeUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.alipay_payee_login_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String alipayPayeeLoginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.alipay_payee_real_name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String alipayPayeeRealName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.wechat_open_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String wechatOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.is_verify
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Byte isVerify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.ishouru_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Integer ishouruId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.is_first_verify
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Byte isFirstVerify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.bank_no
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String bankNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.is_vip
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Byte isVip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.is_geek
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Byte isGeek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.geek_time
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Date geekTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.pinyin
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String pinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.weibo_open_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String weiboOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.qq_open_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String qqOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.wechat_name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String wechatName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.qq_name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String qqName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.weibo_name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String weiboName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.invite_code
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String inviteCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.is_primary_spread
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Byte isPrimarySpread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.is_initialize
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Byte isInitialize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.enterprise_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iq_users.extend
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private String extend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table iq_users
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.id
     *
     * @return the value of iq_users.id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.id
     *
     * @param id the value for iq_users.id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.name
     *
     * @return the value of iq_users.name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.name
     *
     * @param name the value for iq_users.name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.mobile
     *
     * @return the value of iq_users.mobile
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.mobile
     *
     * @param mobile the value for iq_users.mobile
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.avatar
     *
     * @return the value of iq_users.avatar
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.avatar
     *
     * @param avatar the value for iq_users.avatar
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.token
     *
     * @return the value of iq_users.token
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Integer getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.token
     *
     * @param token the value for iq_users.token
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setToken(Integer token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.longitude
     *
     * @return the value of iq_users.longitude
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.longitude
     *
     * @param longitude the value for iq_users.longitude
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.latitude
     *
     * @return the value of iq_users.latitude
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.latitude
     *
     * @param latitude the value for iq_users.latitude
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.address
     *
     * @return the value of iq_users.address
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.address
     *
     * @param address the value for iq_users.address
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.signature
     *
     * @return the value of iq_users.signature
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.signature
     *
     * @param signature the value for iq_users.signature
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.sex
     *
     * @return the value of iq_users.sex
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.sex
     *
     * @param sex the value for iq_users.sex
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.birthday
     *
     * @return the value of iq_users.birthday
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.birthday
     *
     * @param birthday the value for iq_users.birthday
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.city
     *
     * @return the value of iq_users.city
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.city
     *
     * @param city the value for iq_users.city
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.adcode
     *
     * @return the value of iq_users.adcode
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getAdcode() {
        return adcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.adcode
     *
     * @param adcode the value for iq_users.adcode
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setAdcode(String adcode) {
        this.adcode = adcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.citycode
     *
     * @return the value of iq_users.citycode
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.citycode
     *
     * @param citycode the value for iq_users.citycode
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.user_type
     *
     * @return the value of iq_users.user_type
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.user_type
     *
     * @param userType the value for iq_users.user_type
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.evaluate
     *
     * @return the value of iq_users.evaluate
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public BigDecimal getEvaluate() {
        return evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.evaluate
     *
     * @param evaluate the value for iq_users.evaluate
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setEvaluate(BigDecimal evaluate) {
        this.evaluate = evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.follow_nums
     *
     * @return the value of iq_users.follow_nums
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Long getFollowNums() {
        return followNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.follow_nums
     *
     * @param followNums the value for iq_users.follow_nums
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setFollowNums(Long followNums) {
        this.followNums = followNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.follow_me_nums
     *
     * @return the value of iq_users.follow_me_nums
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Long getFollowMeNums() {
        return followMeNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.follow_me_nums
     *
     * @param followMeNums the value for iq_users.follow_me_nums
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setFollowMeNums(Long followMeNums) {
        this.followMeNums = followMeNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.group_nums
     *
     * @return the value of iq_users.group_nums
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Long getGroupNums() {
        return groupNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.group_nums
     *
     * @param groupNums the value for iq_users.group_nums
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setGroupNums(Long groupNums) {
        this.groupNums = groupNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.like_nums
     *
     * @return the value of iq_users.like_nums
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Long getLikeNums() {
        return likeNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.like_nums
     *
     * @param likeNums the value for iq_users.like_nums
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setLikeNums(Long likeNums) {
        this.likeNums = likeNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.like_me_nums
     *
     * @return the value of iq_users.like_me_nums
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Long getLikeMeNums() {
        return likeMeNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.like_me_nums
     *
     * @param likeMeNums the value for iq_users.like_me_nums
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setLikeMeNums(Long likeMeNums) {
        this.likeMeNums = likeMeNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.rong_cloud_token
     *
     * @return the value of iq_users.rong_cloud_token
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getRongCloudToken() {
        return rongCloudToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.rong_cloud_token
     *
     * @param rongCloudToken the value for iq_users.rong_cloud_token
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setRongCloudToken(String rongCloudToken) {
        this.rongCloudToken = rongCloudToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.rong_cloud_id
     *
     * @return the value of iq_users.rong_cloud_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getRongCloudId() {
        return rongCloudId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.rong_cloud_id
     *
     * @param rongCloudId the value for iq_users.rong_cloud_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setRongCloudId(String rongCloudId) {
        this.rongCloudId = rongCloudId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.ayg_id
     *
     * @return the value of iq_users.ayg_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getAygId() {
        return aygId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.ayg_id
     *
     * @param aygId the value for iq_users.ayg_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setAygId(String aygId) {
        this.aygId = aygId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.user_status
     *
     * @return the value of iq_users.user_status
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Byte getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.user_status
     *
     * @param userStatus the value for iq_users.user_status
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setUserStatus(Byte userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.email
     *
     * @return the value of iq_users.email
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.email
     *
     * @param email the value for iq_users.email
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.password
     *
     * @return the value of iq_users.password
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.password
     *
     * @param password the value for iq_users.password
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.created_at
     *
     * @return the value of iq_users.created_at
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.created_at
     *
     * @param createdAt the value for iq_users.created_at
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.updated_at
     *
     * @return the value of iq_users.updated_at
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.updated_at
     *
     * @param updatedAt the value for iq_users.updated_at
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.card_no
     *
     * @return the value of iq_users.card_no
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.card_no
     *
     * @param cardNo the value for iq_users.card_no
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.card_front_image
     *
     * @return the value of iq_users.card_front_image
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getCardFrontImage() {
        return cardFrontImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.card_front_image
     *
     * @param cardFrontImage the value for iq_users.card_front_image
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setCardFrontImage(String cardFrontImage) {
        this.cardFrontImage = cardFrontImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.card_back_image
     *
     * @return the value of iq_users.card_back_image
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getCardBackImage() {
        return cardBackImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.card_back_image
     *
     * @param cardBackImage the value for iq_users.card_back_image
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setCardBackImage(String cardBackImage) {
        this.cardBackImage = cardBackImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.real_name
     *
     * @return the value of iq_users.real_name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.real_name
     *
     * @param realName the value for iq_users.real_name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.alipay_payee_type
     *
     * @return the value of iq_users.alipay_payee_type
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getAlipayPayeeType() {
        return alipayPayeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.alipay_payee_type
     *
     * @param alipayPayeeType the value for iq_users.alipay_payee_type
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setAlipayPayeeType(String alipayPayeeType) {
        this.alipayPayeeType = alipayPayeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.alipay_payee_user_id
     *
     * @return the value of iq_users.alipay_payee_user_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getAlipayPayeeUserId() {
        return alipayPayeeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.alipay_payee_user_id
     *
     * @param alipayPayeeUserId the value for iq_users.alipay_payee_user_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setAlipayPayeeUserId(String alipayPayeeUserId) {
        this.alipayPayeeUserId = alipayPayeeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.alipay_payee_login_id
     *
     * @return the value of iq_users.alipay_payee_login_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getAlipayPayeeLoginId() {
        return alipayPayeeLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.alipay_payee_login_id
     *
     * @param alipayPayeeLoginId the value for iq_users.alipay_payee_login_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setAlipayPayeeLoginId(String alipayPayeeLoginId) {
        this.alipayPayeeLoginId = alipayPayeeLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.alipay_payee_real_name
     *
     * @return the value of iq_users.alipay_payee_real_name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getAlipayPayeeRealName() {
        return alipayPayeeRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.alipay_payee_real_name
     *
     * @param alipayPayeeRealName the value for iq_users.alipay_payee_real_name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setAlipayPayeeRealName(String alipayPayeeRealName) {
        this.alipayPayeeRealName = alipayPayeeRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.wechat_open_id
     *
     * @return the value of iq_users.wechat_open_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getWechatOpenId() {
        return wechatOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.wechat_open_id
     *
     * @param wechatOpenId the value for iq_users.wechat_open_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setWechatOpenId(String wechatOpenId) {
        this.wechatOpenId = wechatOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.is_verify
     *
     * @return the value of iq_users.is_verify
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Byte getIsVerify() {
        return isVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.is_verify
     *
     * @param isVerify the value for iq_users.is_verify
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setIsVerify(Byte isVerify) {
        this.isVerify = isVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.ishouru_id
     *
     * @return the value of iq_users.ishouru_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Integer getIshouruId() {
        return ishouruId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.ishouru_id
     *
     * @param ishouruId the value for iq_users.ishouru_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setIshouruId(Integer ishouruId) {
        this.ishouruId = ishouruId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.is_first_verify
     *
     * @return the value of iq_users.is_first_verify
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Byte getIsFirstVerify() {
        return isFirstVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.is_first_verify
     *
     * @param isFirstVerify the value for iq_users.is_first_verify
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setIsFirstVerify(Byte isFirstVerify) {
        this.isFirstVerify = isFirstVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.bank_no
     *
     * @return the value of iq_users.bank_no
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.bank_no
     *
     * @param bankNo the value for iq_users.bank_no
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.is_vip
     *
     * @return the value of iq_users.is_vip
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Byte getIsVip() {
        return isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.is_vip
     *
     * @param isVip the value for iq_users.is_vip
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setIsVip(Byte isVip) {
        this.isVip = isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.is_geek
     *
     * @return the value of iq_users.is_geek
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Byte getIsGeek() {
        return isGeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.is_geek
     *
     * @param isGeek the value for iq_users.is_geek
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setIsGeek(Byte isGeek) {
        this.isGeek = isGeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.geek_time
     *
     * @return the value of iq_users.geek_time
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Date getGeekTime() {
        return geekTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.geek_time
     *
     * @param geekTime the value for iq_users.geek_time
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setGeekTime(Date geekTime) {
        this.geekTime = geekTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.pinyin
     *
     * @return the value of iq_users.pinyin
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.pinyin
     *
     * @param pinyin the value for iq_users.pinyin
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.weibo_open_id
     *
     * @return the value of iq_users.weibo_open_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getWeiboOpenId() {
        return weiboOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.weibo_open_id
     *
     * @param weiboOpenId the value for iq_users.weibo_open_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setWeiboOpenId(String weiboOpenId) {
        this.weiboOpenId = weiboOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.qq_open_id
     *
     * @return the value of iq_users.qq_open_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getQqOpenId() {
        return qqOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.qq_open_id
     *
     * @param qqOpenId the value for iq_users.qq_open_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setQqOpenId(String qqOpenId) {
        this.qqOpenId = qqOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.wechat_name
     *
     * @return the value of iq_users.wechat_name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getWechatName() {
        return wechatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.wechat_name
     *
     * @param wechatName the value for iq_users.wechat_name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setWechatName(String wechatName) {
        this.wechatName = wechatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.qq_name
     *
     * @return the value of iq_users.qq_name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getQqName() {
        return qqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.qq_name
     *
     * @param qqName the value for iq_users.qq_name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setQqName(String qqName) {
        this.qqName = qqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.weibo_name
     *
     * @return the value of iq_users.weibo_name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getWeiboName() {
        return weiboName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.weibo_name
     *
     * @param weiboName the value for iq_users.weibo_name
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setWeiboName(String weiboName) {
        this.weiboName = weiboName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.invite_code
     *
     * @return the value of iq_users.invite_code
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.invite_code
     *
     * @param inviteCode the value for iq_users.invite_code
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.is_primary_spread
     *
     * @return the value of iq_users.is_primary_spread
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Byte getIsPrimarySpread() {
        return isPrimarySpread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.is_primary_spread
     *
     * @param isPrimarySpread the value for iq_users.is_primary_spread
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setIsPrimarySpread(Byte isPrimarySpread) {
        this.isPrimarySpread = isPrimarySpread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.is_initialize
     *
     * @return the value of iq_users.is_initialize
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Byte getIsInitialize() {
        return isInitialize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.is_initialize
     *
     * @param isInitialize the value for iq_users.is_initialize
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setIsInitialize(Byte isInitialize) {
        this.isInitialize = isInitialize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.enterprise_id
     *
     * @return the value of iq_users.enterprise_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.enterprise_id
     *
     * @param enterpriseId the value for iq_users.enterprise_id
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iq_users.extend
     *
     * @return the value of iq_users.extend
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public String getExtend() {
        return extend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iq_users.extend
     *
     * @param extend the value for iq_users.extend
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    public void setExtend(String extend) {
        this.extend = extend;
    }
}