package com.edu.admin.mapper;

import com.edu.admin.dao.FxUser;
import com.edu.admin.dao.FxUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface FxUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Nov 13 17:51:07 CST 2019
     */
    long countByExample(FxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Nov 13 17:51:07 CST 2019
     */
    int deleteByExample(FxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Nov 13 17:51:07 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Nov 13 17:51:07 CST 2019
     */
    int insert(FxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Nov 13 17:51:07 CST 2019
     */
    int insertSelective(FxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Nov 13 17:51:07 CST 2019
     */
    List<FxUser> selectByExample(FxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Nov 13 17:51:07 CST 2019
     */
    FxUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Nov 13 17:51:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") FxUser record, @Param("example") FxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Nov 13 17:51:07 CST 2019
     */
    int updateByExample(@Param("record") FxUser record, @Param("example") FxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Nov 13 17:51:07 CST 2019
     */
    int updateByPrimaryKeySelective(FxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Nov 13 17:51:07 CST 2019
     */
    int updateByPrimaryKey(FxUser record);
}