package com.example.demo.mapper;

import com.example.demo.dao.FxUser;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface FxUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    int insert(FxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    FxUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    List<FxUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Thu Sep 05 16:29:02 CST 2019
     */
    int updateByPrimaryKey(FxUser record);
}