package com.example.demo.mapper;

import com.example.demo.dao.IqUsers;
import java.util.List;

public interface IqUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iq_users
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iq_users
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    int insert(IqUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iq_users
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    IqUsers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iq_users
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    List<IqUsers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iq_users
     *
     * @mbg.generated Thu Sep 05 13:55:39 CST 2019
     */
    int updateByPrimaryKey(IqUsers record);
}