package com.example.demo.mapper;

import com.example.demo.dao.User;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Sep 05 15:28:57 CST 2019
     */
    int deleteByPrimaryKey(@Param("host") String host, @Param("user") String user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Sep 05 15:28:57 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Sep 05 15:28:57 CST 2019
     */
    User selectByPrimaryKey(@Param("host") String host, @Param("user") String user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Sep 05 15:28:57 CST 2019
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Sep 05 15:28:57 CST 2019
     */
    int updateByPrimaryKey(User record);
}