// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type AchievementsInfo struct {
	ID int `json:"id"`
	// 任务ID
	WorkID *int `json:"workId"`
	// 任务
	PositionTitle *string `json:"positionTitle"`
	// 类型
	PositionType *string `json:"positionType"`
	// 状态
	Status *int `json:"status"`
	// 发放次数
	GiveTimes *int `json:"giveTimes"`
	// 加入时间
	JoinTimes *int `json:"joinTimes"`
}

type AchievementsPagination struct {
	TotalItem int                 `json:"totalItem"`
	TotalPage int                 `json:"totalPage"`
	Items     []*AchievementsInfo `json:"items"`
}

type ApplyCompleteInput struct {
	// 任务参与id
	MemberID int `json:"memberId"`
	// 上传凭证
	ProofFileURL []*string `json:"proofFileUrl"`
}

type AuditJobTemplateInput struct {
	// 岗位模板id
	JobTemplateID int `json:"JobTemplateId"`
	// 服务商id
	ServiceCompanyID int `json:"serviceCompanyId"`
	// 服务商名称
	ServiceCompanyName string `json:"serviceCompanyName"`
	Appid              string `json:"appid"`
	// 客户公司id
	CompanyID int `json:"companyId"`
	// 客户公司名称
	CompanyName string `json:"companyName"`
	// 岗位签约模板id
	SignTemplateID int `json:"signTemplateId"`
	// 岗位模板审核是否通过
	IsAuditPass bool `json:"isAuditPass"`
}

type CategoryInput struct {
	// 类别id
	ID int `json:"id"`
	// 类别名称
	Name string `json:"name"`
	// 1为单选，2为多选
	Type *int `json:"type"`
	// 已选中简历
	Resume []*ResumeInput `json:"resume"`
}

type CategoryType struct {
	// 类别id
	ID int `json:"id"`
	// 类别名称
	Name string `json:"name"`
	// 1为单选，2为多选
	Type int `json:"type"`
	// 已选中简历
	Resume []*ResumeType `json:"resume"`
}

type CommonInput struct {
	Appid          string  `json:"appid"`
	CompanyID      int     `json:"companyId"`
	UserID         *int    `json:"userId"`
	ServiceTypeID  int     `json:"serviceTypeID"`
	Type           int     `json:"type"`
	MediaCoverURL  *string `json:"mediaCoverUrl"`
	MediaUrls      *string `json:"mediaUrls"`
	Name           string  `json:"name"`
	Requirement    string  `json:"requirement"`
	SettlementRule string  `json:"settlementRule"`
	PayType        *int    `json:"payType"`
}

type CommonlyUsedPersonnel struct {
	ID          int     `json:"id"`
	CompanyID   int     `json:"company_id"`
	AppID       string  `json:"app_id"`
	Name        string  `json:"name"`
	CardNo      string  `json:"card_no"`
	BankNo      *string `json:"bank_no"`
	UserID      string  `json:"user_id"`
	Avatar      *string `json:"avatar"`
	Mobile      string  `json:"mobile"`
	Education   *string `json:"education"`
	Address     *string `json:"address"`
	Remark      *string `json:"remark"`
	SigningTime *int    `json:"signing_time"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	DeletedAt   *int    `json:"deleted_at"`
}

type CommonlyUsedPersonnelInfo struct {
	ID int `json:"id"`
	// 姓名
	Name string `json:"name"`
	// 头像
	Avatar *string `json:"avatar"`
	// 手机号码
	Mobile string `json:"mobile"`
	// 身份证号码
	CardNo string `json:"cardNo"`
	// 银行卡号
	BankNo *string `json:"bankNo"`
	// 学历
	Education *string `json:"education"`
	// 地点
	Address *string `json:"address"`
	// 备注
	Remark *string `json:"remark"`
	// 签约时间
	SignTime *int `json:"signTime"`
	// 甲方
	PartyA []*PartyA `json:"partyA"`
	// 乙方
	PartyB *string `json:"partyB"`
}

type CommonlyUsedPersonnelList struct {
	ID int `json:"id"`
	// 用户Id
	UserID *string `json:"userId"`
	// 姓名
	Name *string `json:"name"`
	// 头像
	Avatar *string `json:"avatar"`
	// 手机号
	Mobile *string `json:"mobile"`
	// 地点
	Address *string `json:"address"`
	// 任务
	Position *int `json:"position"`
	// 绩效
	Achievement *int `json:"achievement"`
	// 备注
	Remark *string `json:"remark"`
	// 签约时间
	SignTime *int `json:"signTime"`
	// 创建时间
	CreatedAt *int `json:"createdAt"`
}

type CommonlyUsedPersonnelPagination struct {
	TotalItem int                          `json:"totalItem"`
	TotalPage int                          `json:"totalPage"`
	Items     []*CommonlyUsedPersonnelList `json:"items"`
}

type CompanyStatistics struct {
	// 统计
	Statistics []*WeekStatistics `json:"statistics"`
}

// 创建结算记录条件
type CreateJobSettlementLogInput struct {
	// 岗位WorkID
	WorkID int `json:"workId"`
	// 参与记录ID
	MemberID int `json:"memberId"`
	// 参加者用户ID
	UserID string `json:"userId"`
	// 金额
	Amount float64 `json:"amount"`
	// 文件路径
	File string `json:"file"`
}

type CreateJobTemplateInput struct {
	// 岗位名字(标题)
	Name string `json:"name"`
	// 岗位描述
	Requirement string `json:"requirement"`
	// 结算规则
	SettlementRule string `json:"settlementRule"`
	// 服务类目id
	ServiceTypeID int `json:"serviceTypeId"`
	// 服务类目名称
	ServiceTypeName string `json:"serviceTypeName"`
	// 服务商id
	ServiceCompanyID int `json:"serviceCompanyId"`
	// 服务商名称
	ServiceCompanyName string  `json:"serviceCompanyName"`
	KpiTemplateURL     *string `json:"kpiTemplateUrl"`
	Appid              *string `json:"appid"`
	// 客户公司id
	CompanyID int `json:"companyId"`
	// 客户公司名称
	CompanyName string `json:"companyName"`
	// 岗位签约模板id
	SignTemplateID *int `json:"signTemplateId"`
	// 备注
	Remark *string `json:"remark"`
}

type InviteJoinInput struct {
	// 用户id
	UserID string `json:"userId"`
	// 任务id
	WorkID int `json:"workId"`
}

type Job struct {
	WorkID int `json:"workId"`
	// 任务分类: 1任务, 2任务
	Category int `json:"category"`
	// 支付状态: 余额是否已返回等
	PayStatus *int `json:"payStatus"`
	// 任务状态: 1进行中, 2过期, 3完成
	Progress int `json:"progress"`
	// 可完成人 / 次数
	Quota *int `json:"quota"`
	// 单次任务赏金最小值
	SingleRewardMin float64 `json:"singleRewardMin"`
	// 单次任务赏金最大值
	SingleRewardMax float64 `json:"singleRewardMax"`
	// 评论模式: 是否可以评论, 1是0否, 默认1
	IsCanComment *int `json:"isCanComment"`
	// 凭证模式: 任务是否需要凭证, 1是0否, 默认0
	IsNeedProof int `json:"isNeedProof"`
	// 凭证描述: 上传凭证页面展示描述
	ProofDescription *string `json:"proofDescription"`
	// 凭证类型: 1视频 / 图片, 2其他
	ProofType *int    `json:"proofType"`
	Remark    *string `json:"remark"`
	Extend    *string `json:"extend"`
	UpdatedAt *int    `json:"updatedAt"`
	// 目前工作人数
	MemberCount *int `json:"memberCount"`
	// 绩效条目
	AchievementCount *int `json:"achievementCount"`
	// 未处理人数
	UnprocessCount *int `json:"unprocessCount"`
	// 是否展示任务流程
	IsShowProgress *int `json:"isShowProgress"`
	// 任务模板id
	TemplateID *int `json:"templateId"`
}

type JobInfo struct {
	// work表
	Base *Work `json:"Base"`
	// job表
	Specify *Job `json:"Specify"`
	// member表
	Member *JobMember `json:"Member"`
	// job_template表
	Template *JobTemplate `json:"Template"`
	// 结算信息
	Settlement *Settlement `json:"Settlement"`
}

type JobInput struct {
	// 用户id
	UserID string `json:"userId"`
	// 任务参与id
	MemberID int `json:"memberId"`
}

type JobMember struct {
	ID     int  `json:"id"`
	WorkID *int `json:"workId"`
	// 发布人id
	PublisherID *string `json:"publisherId"`
	// 参与人id
	ParticipantID *string `json:"participantId"`
	// 任务来源: 1申请, 2邀请, 默认申请
	Source *int `json:"source"`
	// 任务状态: 1: 邀请中，2已申请，3已同意参加，4申请完成，5已同意完成，6已评分，7发布者已评分，8互评, 9拒绝申请, 10拒绝完成, 20踢出任务
	Progress *int `json:"progress"`
	// 凭证id: 文件服务url
	ProofFileURL   *string `json:"proofFileUrl"`
	Reward         *int    `json:"reward"`
	AutoCompleteAt *int    `json:"autoCompleteAt"`
	KickOutAt      *int    `json:"kickOutAt"`
	// 参与任务时间
	ParticipateAt      *int    `json:"participateAt"`
	FinishAt           *int    `json:"finishAt"`
	ParticipantContent *string `json:"participantContent"`
	ParticipantScore   *int    `json:"participantScore"`
	PublisherContent   *string `json:"publisherContent"`
	PublisherScore     *int    `json:"publisherScore"`
	RejectReason       *string `json:"rejectReason"`
	// 备注
	Remark    *string `json:"remark"`
	Extend    *string `json:"extend"`
	CreatedAt *int    `json:"createdAt"`
	UpdatedAt *int    `json:"updatedAt"`
	DeletedAt *int    `json:"deletedAt"`
	// 发布者信息
	PublishUser *CommonlyUsedPersonnel `json:"publishUser"`
	// 参与者信息
	ParticipantUser *CommonlyUsedPersonnel `json:"participantUser"`
	// 工作历程
	WorkProgress []*WorkProgress `json:"workProgress"`
	// 结算记录
	LastJobSettlementLog *JobSettlementLog `json:"lastJobSettlementLog"`
}

type JobMemberPagination struct {
	TotalItem int          `json:"totalItem"`
	TotalPage int          `json:"totalPage"`
	Items     []*JobMember `json:"items"`
}

type JobPagination struct {
	PageInfo *PageInfo  `json:"pageInfo"`
	Items    []*JobInfo `json:"items"`
}

// 结算记录
type JobSettlementLog struct {
	// 记录ID
	ID int `json:"id"`
	// 岗位WorkID
	WorkID int `json:"workId"`
	// 参与记录ID
	MemberID int `json:"memberId"`
	// 参加者用户ID
	UserID string `json:"userId"`
	// 流水号
	Sn string `json:"sn"`
	// 金额
	Amount float64 `json:"amount"`
	// 文件路径
	File string `json:"file"`
	// 状态0未确认/1已确认
	Status int `json:"status"`
	// 用户确认时间
	ConfirmAt *int `json:"confirmAt"`
	// 创建时间
	CreatedAt int `json:"createdAt"`
	// 更新时间
	UpdatedAt int `json:"updatedAt"`
	// mark
	Mark *string `json:"mark"`
}

// 分页数据
type JobSettlementLogsPagination struct {
	// 分页
	PageInfo *PageInfo `json:"pageInfo"`
	// 数据
	Items []*JobSettlementLog `json:"items"`
}

// 结算记录
type JobSettlementRecord struct {
	// 记录ID
	ID int `json:"id"`
	// 岗位WorkID
	WorkID int `json:"workId"`
	// 姓名
	Name string `json:"name"`
	// 身份证
	IDCard string `json:"idCard"`
	// 金额
	Amount float64 `json:"amount"`
	// 文件路径
	File string `json:"file"`
	// 创建时间
	CreatedAt int `json:"createdAt"`
	// 更新时间
	UpdatedAt int `json:"updatedAt"`
	// 备注
	Mark *string `json:"mark"`
	// 用户id
	UserID *string `json:"userId"`
	// 参与记录id
	MemberID *int `json:"memberId"`
}

type JobSettlements struct {
	ID          int     `json:"id"`
	BatchID     string  `json:"batch_id"`
	WorkID      int     `json:"work_id"`
	Amount      float64 `json:"amount"`
	SettleCount int     `json:"settle_count"`
	CreatedAt   int     `json:"createdAt"`
	Name        string  `json:"name"`
	CompanyName string  `json:"company_name"`
}

// 绩效总表分页数据
type JobSettlementsPagination struct {
	// 分页
	PageInfo *PageInfo `json:"pageInfo"`
	// 数据
	Items []*JobSettlements `json:"items"`
}

type JobTemplate struct {
	ID int `json:"id"`
	// 岗位名字(标题)
	Name string `json:"name"`
	// 岗位描述
	Requirement string `json:"requirement"`
	// 服务类目id
	ServiceTypeID int `json:"serviceTypeId"`
	// 服务类目名称
	ServiceTypeName *string `json:"serviceTypeName"`
	// 服务商id
	ServiceCompanyID *int `json:"serviceCompanyId"`
	// 服务商名称
	ServiceCompanyName *string `json:"serviceCompanyName"`
	// 结算规则
	SettlementRule string  `json:"settlementRule"`
	KpiTemplateURL *string `json:"kpiTemplateUrl"`
	Appid          *string `json:"appid"`
	// 客户公司id
	CompanyID *int `json:"companyId"`
	// 客户公司名称
	CompanyName *string `json:"companyName"`
	// 岗位签约模板id
	SignTemplateID *int `json:"signTemplateId"`
	// 审核结果  0待审核, 1 通过, 2 拒绝 ,  3.已失效(合同过期), 4 (已审核,合同生效期在未来)未生效,
	IsEnable *int `json:"isEnable"`
	// 审核意见
	Remark *string `json:"remark"`
	// 合同编号
	ContractNo string `json:"contractNo"`
	// 合同开始日期
	ContractStartDate *int `json:"contractStartDate"`
	// 合同结束日期
	ContractEndDate *int `json:"contractEndDate"`
	CreatedAt       *int `json:"createdAt"`
}

type JobTemplateInfo struct {
	Base      *Work        `json:"Base"`
	JobDetail *Job         `json:"JobDetail"`
	Template  *JobTemplate `json:"Template"`
	MediaUrls []*string    `json:"MediaUrls"`
}

type JobTemplatePagination struct {
	PageInfo *PageInfo      `json:"pageInfo"`
	Items    []*JobTemplate `json:"items"`
}

type ListPagination struct {
	TotalItem int        `json:"totalItem"`
	TotalPage int        `json:"totalPage"`
	Items     []*JobInfo `json:"items"`
}

type Message struct {
	Text string `json:"text"`
}

type NewCommonlyUsedPersonnelInput struct {
	// app_id
	AppID string `json:"appId"`
	// 姓名
	Name string `json:"name"`
	// 身份证号码
	CardNo string `json:"cardNo"`
	// 银行卡号
	BankNo *string `json:"bankNo"`
	// 手机
	Mobile string `json:"mobile"`
	// 头像
	Avatar *string `json:"avatar"`
	// 学历
	Education *string `json:"education"`
	// 地址
	Address *string `json:"address"`
	// 备注
	Remark *string `json:"remark"`
	// 公司名
	CompanyName string `json:"companyName"`
}

type NewJobInput struct {
	Appid string `json:"appid"`
	// 客户公司id
	CompanyID int `json:"companyId"`
	// 客户公司名称
	CompanyName string `json:"companyName"`
	UserID      *int   `json:"userId"`
	// 服务类目id
	ServiceTypeID int `json:"serviceTypeID"`
	// 服务类目名称
	ServiceTypeNmae string `json:"serviceTypeNmae"`
	// 服务商id
	ServiceCompanyID int `json:"serviceCompanyId"`
	// 服务商名称
	ServiceCompanyName string `json:"serviceCompanyName"`
	// 媒体类型: 1: 视频任务，2图片任务，3文字任务
	Type int `json:"type"`
	// 任务封面: 用于展示 / im, 文件服务url, 文字任务可不传
	MediaCoverURL *string `json:"mediaCoverUrl"`
	// 媒体地址: 文件服务地址数组 例子 ["url1", "url2"], 文字任务可不传
	MediaUrls []*string `json:"mediaUrls"`
	// 岗位名字(标题)
	Name string `json:"name"`
	// 岗位描述
	Requirement string `json:"requirement"`
	// 结算规则
	SettlementRule string `json:"settlementRule"`
	// 任务类型: 0啥都没, 1预付, 2后支付
	PayType *int `json:"payType"`
	// 任务招募截止时间
	EndAt *int `json:"endAt"`
	// 单次任务赏金最小值
	SingleRewardMin float64 `json:"singleRewardMin"`
	// 单次任务赏金最大值
	SingleRewardMax float64 `json:"singleRewardMax"`
	// 任务模式: 1公开0私密, 默认公开
	IsPublic int `json:"isPublic"`
	// 邀请人员id数组 例子: [1024, 2048, 5096]
	InviteIds []string `json:"inviteIds"`
	// # 凭证类型: 1视频 / 图片, 2其他
	ProofType int `json:"proofType"`
	// 凭证描述: 上传凭证页面展示描述
	ProofDescription *string `json:"proofDescription"`
	// 岗位模板id
	TemplateID *int `json:"templateId"`
	ProfileID  int  `json:"profileId"`
	// 合同编号
	ContractNo string `json:"contractNo"`
	// 合同开始日期
	ContractStartDate int `json:"contractStartDate"`
	// 合同结束日期
	ContractEndDate int `json:"contractEndDate"`
	// 简历选项
	Resume *string `json:"resume"`
}

type PageInfo struct {
	TotalPage int `json:"totalPage"`
	TotalItem int `json:"totalItem"`
}

type PartyA struct {
	CompanyName *string `json:"companyName"`
	SignTime    *string `json:"signTime"`
}

type RedDotCount struct {
	Invite     int `json:"invite"`
	Settlement int `json:"settlement"`
	Job        int `json:"job"`
	All        int `json:"all"`
}

type ResumeInput struct {
	// 简历选项id
	ID int `json:"id"`
	// 简历选项名称
	Name string `json:"name"`
	// 简历选项是否选中
	IsHas *int `json:"isHas"`
}

type ResumeType struct {
	// 简历选项id
	ID int `json:"id"`
	// 简历选项名称
	Name string `json:"name"`
	// 简历选项是否选中
	IsHas int `json:"isHas"`
}

// 岗位搜索条件体
type SearchJobInput struct {
	// 开始时间
	Beign *int `json:"beign"`
	// 结束时间
	End *int `json:"end"`
	ID  *int `json:"id"`
	// 标题
	Name *string `json:"name"`
	// 状态
	Status *int `json:"status"`
	// 服务类目id
	ServiceTypeID *int `json:"serviceTypeId"`
}

// 搜索岗位模板条件体
type SearchJobTemplateInput struct {
	ID *int `json:"id"`
	// 标题
	Name *string `json:"name"`
	// 服务类目id
	ServiceTypeID *int `json:"serviceTypeId"`
}

type Settlement struct {
	ID        int      `json:"id"`
	File      *string  `json:"file"`
	Status    *int     `json:"status"`
	Amount    *float64 `json:"amount"`
	CreatedAt *int     `json:"created_at"`
}

type SettlementList struct {
	Key     string                 `json:"key"`
	Success []*JobSettlementRecord `json:"success"`
	Error   []*JobSettlementRecord `json:"error"`
}

type SignInput struct {
	// work_id
	WorkID int `json:"WorkId"`
	// 手机号
	Mobile *string `json:"Mobile"`
}

type SignRspData struct {
	// 签约状态  SIGNING： 签约中, CLOSED：签约完成
	State *string `json:"state"`
	// 签约描述
	StateDesc *string `json:"StateDesc"`
	// 接受状态  ACCEPTED： 接受签约
	ResultCode *string `json:"resultCode"`
	// 接受信息
	ResultMessage *string `json:"ResultMessage"`
	// 手动签约跳转地址 先用c， 为空， 判断b,b不为空则用B，bc为空是自动签约
	PartybSignURL *string `json:"PartybSignUrl"`
	PartycSignURL *string `json:"PartycSignUrl"`
	ExtrSystemID  *string `json:"ExtrSystemId"`
	PreviewURL    *string `json:"previewUrl"`
}

type Statistics struct {
	// 任务
	Job *JobStatistics `json:"job"`
	// 人员
	Member *MemberStatistics `json:"member"`
	// 签约数据
	Sign []*SignStatistics `json:"sign"`
}

type Template struct {
	CompanyName        *string `json:"companyName"`
	ServiceCompanyName *string `json:"serviceCompanyName"`
	ServiceTypeName    *string `json:"serviceTypeName"`
	SettlementRule     *string `json:"settlementRule"`
}

type UpdateCommonlyUsedPersonnelInput struct {
	// 用户id
	UserID *string `json:"userId"`
	// 姓名
	Name *string `json:"name"`
	// 头像
	Avatar *string `json:"avatar"`
	// 手机号码
	Mobile *string `json:"mobile"`
	// 银行卡号
	BankNo *string `json:"bankNo"`
	// 学历
	Education *string `json:"education"`
	// 地点
	Address *string `json:"address"`
	// 备注
	Remark *string `json:"remark"`
	// 签约时间
	SignTime *int `json:"signTime"`
}

// 更新岗位
type UpdateJobInput struct {
	WorkID int `json:"workId"`
	// 备注
	Remark string `json:"remark"`
}

// 更新结算记录条件
type UpdateJobSettlementLogInput struct {
	ID int `json:"id"`
	// 岗位WorkID
	WorkID int `json:"workId"`
	// 参与记录ID
	MemberID int `json:"memberId"`
	// 参加者用户ID
	UserID string `json:"userId"`
	// 金额
	Amount float64 `json:"amount"`
	// 文件路径
	File string `json:"file"`
}

type UploadFile struct {
	ID   int            `json:"id"`
	File graphql.Upload `json:"file"`
}

type UploadRecordPagination struct {
	TotalItem int             `json:"totalItem"`
	TotalPage int             `json:"totalPage"`
	Items     []*UploadRecord `json:"items"`
}

type UserFlowPagination struct {
	TotalItem int         `json:"totalItem"`
	TotalPage int         `json:"totalPage"`
	Items     []*UserFlow `json:"items"`
}

type VerifiedInput struct {
	IDCardFront string  `json:"idCardFront"`
	IDCardBack  string  `json:"idCardBack"`
	IDCardNo    string  `json:"idCardNo"`
	BankCardNo  string  `json:"bankCardNo"`
	Name        string  `json:"name"`
	Mobile      *string `json:"mobile"`
}

type Work struct {
	ID        int    `json:"id"`
	Appid     string `json:"appid"`
	CompanyID int    `json:"companyId"`
	UserID    string `json:"userId"`
	// 服务类型id
	ServiceTypeID int `json:"serviceTypeID"`
	// work类型 1任务2任务
	WorkType *int `json:"workType"`
	// work名
	Name string `json:"name"`
	// work描述
	Requirement string `json:"requirement"`
	// 任务类型: 0啥都没, 1预付, 2后支付
	PayType *int `json:"payType"`
	// 任务时长: 默认72H
	Duration *int `json:"duration"`
	// 任务招募截止时间
	EndAt *int `json:"endAt"`
	// 发布来源: 1app, 2小善小程序后台, 3税筹
	Source *int `json:"source"`
	// # 是否正常: 1正常,2拒绝, 3已失效(失效,合同到期) , 4: 未生效(已通过审核,但是合同时间没到,没有生效), 5.删除,  7审核中
	Status *int `json:"status"`
	// 媒体类型: 1: 视频任务，2图片任务，3文字任务
	Type *int `json:"type"`
	// 任务模式: 1公开0私密, 默认公开
	IsPublic int `json:"isPublic"`
	// 任务封面: 用于展示 / im, 文件服务url
	MediaCoverURL *string `json:"mediaCoverUrl"`
	// 媒体地址: 文件服务地址数组
	MediaUrls []*string `json:"mediaUrls"`
	// 简历
	Resume    *string `json:"resume"`
	Extend    *string `json:"extend"`
	CreatedAt *int    `json:"createdAt"`
}

type WorkProgress struct {
	ID int `json:"id"`
	// appid
	AppID *string `json:"appId"`
	// 任务参与者
	ParticipantID *string `json:"participantId"`
	// 任务发布者
	PublisherID *string `json:"publisherId"`
	// 任务id
	WorkID *int `json:"workId"`
	// 历程类型: created发布任务, apply申请参加任务, refuse拒绝参加任务, approve同意参加任务, invite邀请任务, refuse_invite拒绝邀请, approve_invite同意邀请参加任务, apply_complete申请完成任务 / 上传凭证, complete完成任务, refuse_complete拒绝完成任务, master_mark主态评价, guest_mark客态评价, kick_member服务者超时未完成任务, complete_auto需求者同意完成超时,
	Type      *string `json:"type"`
	Extend    *string `json:"extend"`
	CreatedAt *int    `json:"createdAt"`
	UpdatedAt *int    `json:"updatedAt"`
	// 发布者信息
	PublishUser *CommonlyUsedPersonnel `json:"publishUser"`
	// 参与者信息
	ParticipantUser *CommonlyUsedPersonnel `json:"participantUser"`
}

type ImportStatus struct {
	ID     string `json:"id"`
	Status bool   `json:"Status"`
	Total  int    `json:"Total"`
}

type JobStatistics struct {
	// 任务统计
	JobCount *int `json:"jobCount"`
	// 任务人员统计
	JobMemberCount *int `json:"jobMemberCount"`
}

type MemberStatistics struct {
	// 任务人员统计
	JoinMember *int `json:"joinMember"`
	// 任务签约数据统计
	SignMember *int `json:"signMember"`
	// 待处理条数
	ToDoCount *int `json:"ToDoCount"`
}

type SignStatistics struct {
	// 服务商id
	ServiceCompanyID *int `json:"serviceCompanyId"`
	// 服务商名
	ServiceCompanyName *string `json:"serviceCompanyName"`
	// 服务类型名
	ServiceTypeName *string `json:"serviceTypeName"`
}

type UploadRecord struct {
	ID        int      `json:"id"`
	CreatedAt int      `json:"createdAt"`
	File      []string `json:"file"`
}

type UserFlow struct {
	Amount         *float64 `json:"amount"`
	PayOrderItemID *string  `json:"payOrderItemId"`
	PaymentResTime *string  `json:"paymentResTime"`
}

type WeekStatistics struct {
	// 天
	Day *string `json:"day"`
	// 发放金额
	Money *float64 `json:"money"`
	// 发放次数
	Count *int `json:"count"`
}
